auth:
  type: DISABLED
kafka:
  clusters:
    - bootstrapServers: kafka-1:19092
      name: local
      properties: {}
      readOnly: false
      schemaRegistry: http://schema-registry:8083
rbac:
  roles: []
webclient: {}
