app:
  scheduler:
    enable: true
    interval: 60s
    force-check-delay: 60s
    max-links-per-check: 100
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  database-access-type: jpa
  migrations-path: migrations
  message-transport: Kafka
  kafka:
    updates-topic-name: updates
  rate-limiter:
    limit-for-period: 10
    limit-refresh-period: 1s
    timeout-duration: 100ms

provider:
  github:
    url: https://api.github.com
  stackoverflow:
    url: https://api.stackexchange.com/2.3

bot:
  url: ${BOT_URL:http://localhost:8090}
  response-timeout: 400ms

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
    change-log: ../../../../migrations/master.xml
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost:5433}/scrapper
    username: postgres
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:19092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        schema.registry.url: http://localhost:8083

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  structured:
    format:
      file: ecs
  file:
    name: logs/scrapper-log.json

resilience4j:
  retry:
    instances:
      botRetry:
        maxAttempts: 3
        waitDuration: 400ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
  circuitbreaker:
    instances:
      botCircuitBreaker:
        failureRateThreshold: 50 # % failures to open circuit
        minimumNumberOfCalls: 8 # min calls before calculating failure rate
        slidingWindowSize: 10 # number of calls to track
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 10s # time to wait before trying again
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: false
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
