app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost:5432}/scrapper
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: optional:file:./application.env

server:
  port: 8090

scrapper:
  url: ${SCRAPPER_URL:http://localhost:8081}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  structured:
    format:
      console: ecs
  file:
    name: log.json
