app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  kafka:
    updates-topic-name: updates
  redis:
    cache-ttl: 600
    list-command-cache-prefix: "tracked_links:"

spring:
  application:
    name: Bot
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 5000
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:19092}
    consumer:
      group-id: bot
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: backend.academy.bot.dto.request.LinkUpdate
      auto-offset-reset: earliest

server:
  port: 8090

scrapper:
  url: ${SCRAPPER_URL:http://localhost:8081}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
#  structured:
#    format:
#      console: ecs
  file:
    name: logs/bot-log.json
